#!/bin/bash

JR_ROOT="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
JR_USER=`whoami`

source "$JR_ROOT/res/sh/config.sh"

usage(){
	echo "Usage: jr_client <INSTANCE> <PATH> <CURL OPTIONS>"
	exit 1
}

#
# get instance
#
JR_INSTANCE=$1

[ -z $JR_INSTANCE ] && usage
[[ "$JR_INSTANCE" =~ ^[a-zA-Z0-9_-]+$ ]] || jr_fail "Instance name $JR_INSTANCE is invalid. Can only contain letters, numbers, hyphens and underscores."
[ -d "$JR_DATADIR/$JR_INSTANCE" ] || jr_fail "Instance $JR_INSTANCE does not exist."

shift

#
# get path
#

URL="127.0.0.1:$JR_PORT/$1"
shift

#
# get token
#

TOKEN=$(node "$JR_ROOT/res/js/token.js" "$JR_INSTANCE" rwx 1 )
echo Executing curl -H "Authorization: Bearer $TOKEN" "$URL" "$@" >&2
curl -H "Authorization: Bearer $TOKEN" "$URL" "$@"
