from nginx

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
   php \
   php-fpm \
   nodejs \
   sudo \
   wget \
   vim \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# json_risk requires a user to run
RUN useradd -ms /bin/bash celery

# start server via docker entry point
COPY entry_point_script.sh .
ENTRYPOINT /entry_point_script.sh
